### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by delirious-lettuce**
### Summary:

* Simplify boolean expressions
* Use `is` and `is not` for comparisons with None
* Create dicts using dict literals
* Create lists usings list literals
* Use `self` as methods first parameter
* Remove redundant parentheses
* Use triple-quoted docstrings
* Remove trailing semicolon
* Remove unnecessary backslashes
* Fix typos
    * `quoteed` -> `quoted`
    * `overriden` -> `overridden`
    * `modifiying` -> `modifying`
    * `follwing` -> `following`
    * `explictly` -> `explicitly`
    * `transation` -> `transaction`
    * `occurences` -> `occurrences`
    * `successfull` -> `successful`
    * `libary` -> `library`

### CODE REVIEW

**Comment by aartur** [comment]
I'll merge only the typo fixes and drop the rest:

- I don't want to enforce a strict code style (ie. tuple formatting or list creation)
- the csv.py module is taken from the stdlib and shouldn't be refactored
- the "Simplify boolean expressions" cleanup makes the code incorrect: the `execute_lwt` function returns three values: `None`, `False` and `True` that should be distinguished

**Comment by delirious-lettuce** [comment]
@aartur ,

My mistake after the call to `execute_lwt`, I had intended to move the `is None` check above the `not lwt_res` check but clearly I forgot! Other than that, using `== False` (or `== True`) is frowned upon in Python.

http://pep8.org/#programming-recommendations

> Don’t compare boolean values to True or False using ==. :
> 
> Yes:
> 
> `if greeting:`
> No:
> 
> `if greeting == True:`
> Worse:
> 
> `if greeting is True:`

Also, you reverting the `is None` part is quite odd. There are many examples in your project of using the correct `is` comparisons for `None` so to revert this one is actually inconsistent with your own code.

> Comparisons to singletons like None should always be done with is or is not, never the equality operators.

---
> I don't want to enforce a strict code style (ie. tuple formatting or list creation)

It doesn't bother me if you really prefer redundant parentheses, to each their own, but do you actually think this...

```python
res = []
res.append('')
```
is better than this?

```python
res = ['']
```

The bytecode shows that this style only adds unnecessary complexity... ["Simple is better than complex."](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python)

```python
>>> import dis
>>> dis.dis("res = [];res.append('')")
  1           0 BUILD_LIST               0
              2 STORE_NAME               0 (res)
              4 LOAD_NAME                0 (res)
              6 LOAD_ATTR                1 (append)
              8 LOAD_CONST               0 ('')
             10 CALL_FUNCTION            1
             12 POP_TOP
             14 LOAD_CONST               1 (None)
             16 RETURN_VALUE
>>> dis.dis("res = ['']")
  1           0 LOAD_CONST               0 ('')
              2 BUILD_LIST               1
              4 STORE_NAME               0 (res)
              6 LOAD_CONST               1 (None)
              8 RETURN_VALUE
```

Here is another example you reverted, which also seems to become more complex due to your preferred style.

```python
>>> dis.dis("""\
... data = {}
... data['report_name'] = self.tile.report.report_name
... data['latest_extra_ri_data'] = {}
... """)
  1           0 BUILD_MAP                0
              2 STORE_NAME               0 (data)

  2           4 LOAD_NAME                1 (self)
              6 LOAD_ATTR                2 (tile)
              8 LOAD_ATTR                3 (report)
             10 LOAD_ATTR                4 (report_name)
             12 LOAD_NAME                0 (data)
             14 LOAD_CONST               0 ('report_name')
             16 STORE_SUBSCR

  3          18 BUILD_MAP                0
             20 LOAD_NAME                0 (data)
             22 LOAD_CONST               1 ('latest_extra_ri_data')
             24 STORE_SUBSCR
             26 LOAD_CONST               2 (None)
             28 RETURN_VALUE
>>> dis.dis("""\
... data = {'report_name': self.tile.report.report_name,
...         'latest_extra_ri_data': {}}
... """)
  1           0 LOAD_NAME                0 (self)
              2 LOAD_ATTR                1 (tile)
              4 LOAD_ATTR                2 (report)
              6 LOAD_ATTR                3 (report_name)

  2           8 BUILD_MAP                0
             10 LOAD_CONST               0 (('report_name', 'latest_extra_ri_data'))
             12 BUILD_CONST_KEY_MAP      2
             14 STORE_NAME               4 (data)
             16 LOAD_CONST               1 (None)
             18 RETURN_VALUE
```

---
> I'll merge only the typo fixes and drop the rest:

You reverted typo fixes:

* `quoteed` -> `quoted`
* `occurences` -> `occurrences`

---
Overall, the most amusing one has to be that you reverted a single trailing semi-colon in `test_csv.py`.

Good luck with your project!

**Comment by aartur** [comment]
I just think that readability is more important than microoptimizations or strict adherence to the PEP. I'm not saying that my version is better than yours - if you would submit new code using your rules I would happily accept it. But if the code is correct, I don't see a need for small style enhancements.

> Other than that, using == False (or == True) is frowned upon in Python.

Yes, but the case is special as the function returns three values and uses `==` for the sake of uniformity.

> this...
> 
> res = []
> res.append('')
> is better than this?
> 
> res = ['']

It depends - if the algorithm works by putting multiple independent values into the list and there is no "initial value", it makes expressing the intent more clear. And it's easier to put prints or debugger breaks between the steps.

> The bytecode shows that this style only adds unnecessary complexity... "Simple is better than complex."

I think the statement addresses source code more than bytecode...

> You reverted typo  fixes:

Sorry for that, I'll fix it later.

> Overall, the most amusing one has to be that you reverted a single trailing semi-colon in test_csv.py.

The *csv* modules are copied from Python's stdlib and I wouldn't want to refactor them (to make applying patches for future versions easier).

**Comment by delirious-lettuce** [comment]
@aartur ,

Thanks for the reply!

> I just think that readability is more important than microoptimizations or strict adherence to the PEP.

Of course readability counts, but reverting the list literals seems to have the opposite effect. Strict adherence to PEP8 was not what this PR was about, there would have to be many more changes for that.

---
> Yes, but the case is special as the function returns three values and uses == for the sake of uniformity.

It is interesting that uniformity is now a concern of yours. You reverted the `is None` back to `== None` even though your project has many other cases where `is None` and `is not None` are used.

* > Special cases aren't special enough to break the rules. - The Zen of Python, by Tim Peters

---
> And it's easier to put prints or debugger breaks between the steps.

You are joking right... you think you need to debug in between `res = []` and `res.append('')`?

---
> I think the statement addresses source code more than bytecode...

Again, `res = []` (hint: source code...) is simpler than `res = []; res.append('')` in every sense of the word.

> The csv modules are copied from Python's stdlib and I wouldn't want to refactor them (to make applying patches for future versions easier).

You skipped right over my comment. Your copy/pasted `csv.py` version does not match either one of the latest Python 2 or 3 versions from the CPython GitHub. So, either you modified the `csv.py` code yourself or you copy/pasted it from an older version that I didn't check. The reason I lean towards the former is that if you didn't modify it at all, you could just import it from the standard library (making `csv.py` and `test_csv.py` unnecessary files in your project).

**Pull request merged**
