### PR TITLE
first stab at docker support

### PR DESCRIPTION
**Pull request by sedgewickmm18**

### CODE REVIEW

**Comment by aartur** [comment]
Thanks for the contribution.

I see a few problems with the scripts:
- Monique Web and Monique API specify exact versions of the monique library in requirements.txt, and you are fetching Git clones - it might result in errors due to incompatibilites of the Web and API apps with the newest git versions
- the "create table user..." shouldn't be hardcoded and should be executed from the file from the Monique Web repo
- I think executing the test createdashboard.py script is not necessary 

The other thing is that the "monique" repo is meant for the library code and should be free of deployment scripts. I think the best approach would be to create a separate repo for the docker scripts and upload the image to the Docker Hub, and add a link to it to the Monique Web's README. This has the added benefit of the availability of a ready image.

**Comment by sedgewickmm18** [comment]
Thanks for your review

- What would be your proposal with regard to requirements ? I prefer not to go with a separate hard-coded version.
- Without create table user .. the container doesn't work and returns a 500 error, so the required table is not created in the table initialization step.
- I left the test in so that the build breaks in case something's wrong.
I can certainly create a separate repository for the docker files if you add me to monique-dashboard's ACL.

**Comment by aartur** [comment]
- monique-api and monique-web already specify monique in requirements.txt, so it's installed automatically
- the "users" table is a part of monique-web migrations: https://github.com/monique-dashboards/monique-web#executing-database-migrations

I wouldn't want to support a docker repo as a part of monique-dashboards project - the main artifact of the project is the library, and the API and the Web apps are sample projects using the library. If you want to create the docker repo please create it by yourself, it can be linked from the Monique Web README as community contribution. I suggested creating a separate repo because it seems it's required for uploading an image to Docker Hub, and a ready working image would be most helpful for others,

**Comment by sedgewickmm18** [comment]
Done. 
If you like just have a closer look my monique-docker repositories on github and docker hub. I'm closing this pull request now; thanks for your help.
BTW, I checked the migration step and it seems that the user table is not created, so I'm doing it in the build script for now.

**Comment by aartur** [comment]
The table is defined here https://github.com/monique-dashboards/monique-web/blob/master/mqeweb/migrations/m20170100000000_users.sqlite3

**Pull request closed without merging**
